name: metatest
on:
  push:
    branches: 
      - main
jobs:
  info_commands:
    runs-on: ubuntu-latest
    steps:
      - uses: vapor/ci@v0.1
        id: unit-test-swift-versions
        with:
          command: unit-test-swift-versions
      - run: echo unit-test-swift-versions ${{ steps.unit-test-swift-versions.outputs.data }}
        shell: bash
